[build]
  command = "npm run build && cd netlify/functions && npm install"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/apply"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
